### ISSUE TITLE
import issue 

### ISSUE THREAD

**Issue by netwrkspider** [sumsted/pyssml#1]
when importing PySSML its give an error.

Traceback (most recent call last):
  File "gtiai.py", line 9, in <module>
    from pyssml.PySSML import PySSML
  File "/usr/local/lib/python2.7/dist-packages/pyssml/PySSML.py", line 16, in <module>
    import urllib.parse
ImportError: No module named parse

**Comment by ejm** [comment]
It would appear this module was designed for Python 3, you are currently running Python 2.7. Would it be possible for you to migrate code to Python 3?

**Comment by netwrkspider** [comment]
Yup sure will try to migrate my code with python3 thanks.
